Repository IntersectMBO/cardano-node, pull requests merged in 2020-10, with the labels that each got.

#1934 cardano-api: Fix haddock build
  cardano-api/src/Cardano/Api/Byron.hs
  cardano-api/src/Cardano/Api/Shelley.hs
Labels: bug, documentation

#1953 Replace typo "906185" with "8520857" in KES_period.md
  doc/stake-pool-operations/KES_period.md
Labels: documentation

#1986 Fix cardano-api haddock build again
  cardano-api/src/Cardano/Api/Byron.hs
  cardano-api/src/Cardano/Api/Shelley.hs
Labels: bug
