Repository IntersectMBO/cardano-node, pull requests merged in 2020-08, with the labels that each got.

#1552 fixes LiveView memory display
  cardano-node/src/Cardano/Node/TUI/EventHandler.hs
Labels: bug, logging and monitoring, priority low

#1503 CAD-1385: Show KES values in LiveView.
  cardano-node/src/Cardano/Node/TUI/Drawing.hs
  cardano-node/src/Cardano/Node/TUI/EventHandler.hs
Labels: enhancement, logging and monitoring

#1569 CAD-1395: LiveView, correct quitting.
  cardano-node/src/Cardano/Node/TUI/EventHandler.hs
Labels: bug, logging and monitoring

#1741 [DOCS] Logo change
  doc/.sphinx/cardano-logo.png
  doc/conf.py
Labels: documentation
