Repository IntersectMBO/cardano-node, pull requests merged in 2020-02, with the labels that each got.

#533 CAD-476 extract more metrics from logs
  benchmarking/chain-sync/analyse-logs.sh
Labels: byron

#534 CAD-445 LiveView displays node id
  cardano-node/src/Cardano/Node/TUI/LiveView.hs
Labels: byron

#536 reenable 'stack build'
  stack.yaml
Labels: bug

#548 Create `Benchmarking` folder for relevant modules
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/CLI/Benchmarking/Tx/Generation.hs
  cardano-node/src/Cardano/CLI/Benchmarking/Tx/NodeToNode.hs
  cardano-node/src/Cardano/CLI/Benchmarking/Tx/TxSubmission.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/CLI/Tx.hs
  cardano-node/src/Cardano/Node/Submission.hs
  cardano-node/src/Cardano/Node/TxSubClient.hs
Labels: maintenance

#580 Add gzip to buildTools
  scripts/buildkite/default.nix
Labels: nix, priority high

#581 Fix args for running from cabal
  benchmarking/cluster3nodes/run-3node-cluster.sh
Labels: bug

#583 node service: make the socket path spec work in single-service mode as well
  nix/nixos/cardano-cluster-service.nix
  nix/nixos/cardano-node-service.nix
Labels: byron, chairman, nix, priority high

#587 Fix PR template to automatically show checkboxes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance, priority low

#592 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance, priority low

#590 CAD-636: repair the JournalSK presentation
  cardano-node/src/Cardano/Tracing/ToObjectOrphans.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  configuration/log-configuration.yaml
Labels: byron, enhancement, priority medium

#591 Get local node tip information
  cardano-node/README.md
  cardano-node/app/cardano-cli.hs
  cardano-node/src/Cardano/CLI/Genesis.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Parsers.hs
  cardano-node/src/Cardano/CLI/Run.hs
Labels: byron, enhancement, priority high

#602 dockerImage: rename docker env
  nix/docker.nix
Labels: nix

#594 CAD-328 context name in Trace; adaptations to upstream changes
  cabal.project
  cardano-node/app/wallet-client.hs
  cardano-node/src/Cardano/CLI/Benchmarking/Tx/NodeToNode.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Node/TUI/LiveView.hs
  cardano-node/src/Cardano/Tracing/MicroBenchmarking.hs
  cardano-node/src/Cardano/Tracing/ToObjectOrphans.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  stack.yaml
Labels: byron

#607 Update scripts.nix
  nix/scripts.nix
Labels: bug, byron
