Repository IntersectMBO/cardano-node, pull requests merged in 2020-06, with the labels that each got.

#1135 SRE-100 musl64 and macos release builds
  default.nix
  nix/binary-release.nix
  nix/default.nix
  nix/haskell.nix
  nix/sources.nix
  nix/windows-release.nix
  release.nix
  shell.nix
Labels: nix

#1288 CAD-1247 update iohk-monitoring fw
  cabal.project
  cardano-config/src/Cardano/Config/Logging.hs
  cardano-config/src/Cardano/TracingOrphanInstances/Common.hs
  stack.yaml
Labels: maintenance, priority medium

#1153 Nixpkgs 20.03
  nix/sources.json
Labels: nix

#1317 Simplifies the Docker image to enable more freedom at runtime and better correlation with the underlying interface
  nix/docker.nix
Labels: enhancement

#1315 CAD-1262: Remove 'Forks created' metric.
  cardano-node/src/Cardano/Node/TUI/Drawing.hs
  cardano-node/src/Cardano/Node/TUI/EventHandler.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: bug
