Repository IntersectMBO/cardano-node, pull requests merged in 2020-03, with the labels that each got.

#615 Remove `stack build` CI job
  .buildkite/pipeline.yml
  scripts/buildkite/default.nix
  scripts/buildkite/rebuild.hs
  scripts/buildkite/stack-hpc-coveralls.nix
Labels: maintenance

#545 Add CBOR pretty print and validation commands to `cardano-cli`
  cabal.project
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/README.md
  cardano-node/app/cardano-cli.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Parsers.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/Common/Parsers.hs
  stack.yaml
Labels: enhancement, priority low

#622 CAD-707 adapt configs to namespace changes
  benchmarking/chain-sync/configuration/log-config-ci.yaml
  benchmarking/chain-sync/configuration/log-configuration.yaml
  benchmarking/cluster3nodes/configuration/log-config-0.yaml
  benchmarking/cluster3nodes/configuration/log-config-1.yaml
  benchmarking/cluster3nodes/configuration/log-config-2.yaml
  benchmarking/cluster3nodes/configuration/log-config-generator.yaml
  benchmarking/cluster3nodes/configuration/log-config-genesis.yaml
  configuration/configuration-mainnet.yaml
  configuration/configuration-silent.yaml
  configuration/log-config-0.liveview.yaml
  configuration/log-config-0.yaml
  configuration/log-config-1.liveview.yaml
  configuration/log-config-1.yaml
  configuration/log-config-2.liveview.yaml
  configuration/log-config-2.yaml
  configuration/log-configuration.yaml
Labels: bug, byron

#631 CAD-708 CAD-707 integrate upstream changes
  cabal.project
  nix/sources.json
  stack.yaml
Labels: byron

#637 CAD-508 ouroboros-network: bump to master
  cabal.project
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
  cardano-node/src/Cardano/Tracing/MicroBenchmarking.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  stack.yaml
Labels: maintenance

#612 Add `GenesisFile` and `SocketPath` fields to yaml file
  benchmarking/chain-sync/configuration/log-config-ci.yaml
  benchmarking/chain-sync/configuration/log-configuration.yaml
  benchmarking/cluster3nodes/configuration/log-config-0.yaml
  benchmarking/cluster3nodes/configuration/log-config-1.yaml
  benchmarking/cluster3nodes/configuration/log-config-2.yaml
  benchmarking/cluster3nodes/configuration/log-config-generator.yaml
  benchmarking/cluster3nodes/configuration/log-config-genesis.yaml
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/README.md
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Parsers.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/Common/LocalSocket.hs
  cardano-node/src/Cardano/Common/Parsers.hs
  cardano-node/src/Cardano/Node/Run.hs
  configuration/configuration-mainnet.yaml
  configuration/configuration-silent.yaml
  configuration/log-config-0.liveview.yaml
  configuration/log-config-0.yaml
  configuration/log-config-1.liveview.yaml
  configuration/log-config-1.yaml
  configuration/log-config-2.liveview.yaml
  configuration/log-config-2.yaml
  configuration/log-configuration.yaml
  nix/svclib.nix
  scripts/issue-genesis-utxo-expenditure.sh
  scripts/issue-utxo-expenditure.sh
  scripts/submit-tx.sh
Labels: maintenance

#630 Add `version` command to `cardano-cli`
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/CLI/Parsers.hs
  cardano-node/src/Cardano/CLI/Run.hs
Labels: enhancement

#633 Propagate `TraceLocalErrorPolicy` to all config yaml files
  benchmarking/chain-sync/configuration/log-configuration.yaml
  benchmarking/cluster3nodes/configuration/log-config-0.yaml
  benchmarking/cluster3nodes/configuration/log-config-1.yaml
  benchmarking/cluster3nodes/configuration/log-config-2.yaml
  benchmarking/cluster3nodes/configuration/log-config-generator.yaml
  benchmarking/cluster3nodes/configuration/log-config-genesis.yaml
  configuration/configuration-mainnet.yaml
  configuration/configuration-silent.yaml
  configuration/log-config-0.liveview.yaml
  configuration/log-config-0.yaml
  configuration/log-config-1.liveview.yaml
  configuration/log-config-1.yaml
  configuration/log-config-2.liveview.yaml
  configuration/log-config-2.yaml
Labels: maintenance

#628 CAD-701: Move tx-gen to a separate cabal-package.
  cabal.project
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/Node/TxSubClient.hs
  cardano-tx-generator/ChangeLog.md
  cardano-tx-generator/LICENSE
  cardano-tx-generator/NOTICE
  cardano-tx-generator/README.md
  cardano-tx-generator/app/cardano-tx-generator.hs
  cardano-tx-generator/cardano-tx-generator.cabal
  cardano-tx-generator/docs/tx-submit-using-tx-gen.md
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Parsers.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Run.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Error.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/NodeToNode.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Submission.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Tx.hs
  cardano-tx-generator/test/Spec.hs
  stack.yaml
Labels: byron

#653 CAD-650 trace block forge time
  cabal.project
  cardano-node/src/Cardano/Tracing/MicroBenchmarking.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  stack.yaml
Labels: byron

#659 CAD-722 correct context name of internal metrics
  cardano-node/src/Cardano/Node/TUI/LiveView.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: bug, byron

#663 CAD-721 expand TraceLabelPeer messages
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
Labels: bug, byron

#665 Remove wallet
  cardano-node/app/wallet-client.hs
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/Wallet/Client.hs
  cardano-node/src/Cardano/Wallet/Logging.hs
  cardano-node/src/Cardano/Wallet/Run.hs
  scripts/SCRIPTS.md
  scripts/start-wallet.sh
Labels: maintenance

#655 Improve `ProtocolInstantiationError` rendering
  cardano-config/cardano-config.cabal
  cardano-config/src/Cardano/Config/Protocol.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/Node/Run.hs
Labels: enhancement

#670 CAD-508: rename the serialised blockfetch trace to BlockFetchProtocolSerialised
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: maintenance, priority low

#614 nix shell: eliminate the need to build ouroboros-{consensus,network}
  .buildkite/pipeline.yml
  shell.nix
Labels: enhancement, maintenance, nix

#668 CAD-508: update traces for Tx throughput benchmarking
  cardano-config/src/Cardano/Config/Protocol.hs
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: maintenance, priority medium

#673 Fix `validate-cbor` command
  cardano-node/src/Cardano/CLI/Ops.hs
Labels: maintenance

#669 Add Windows build and tests to required hydra job.
  nix/nixos/cardano-cluster-service.nix
  nix/nixos/cardano-node-service.nix
  nix/nixos/chairman-as-a-service.nix
  nix/sources.json
  nix/svclib.nix
  release.nix
Labels: byron, priority high

#683 Remove genesis-hash and genesis-file arguments from cardano-node
  benchmarking/chain-sync/benchmark-chain-sync-mainnet.sh
  benchmarking/chain-sync/configuration/log-configuration.yaml
  benchmarking/cluster3nodes/run-3node-cluster.sh
  cardano-config/src/Cardano/Config/CommonCLI.hs
  cardano-config/src/Cardano/Config/Logging.hs
  cardano-config/src/Cardano/Config/Protocol.hs
  cardano-config/src/Cardano/Config/Topology.hs
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/README.md
  cardano-node/app/cardano-node.hs
  cardano-node/app/chairman.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/Common/Parsers.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Node/TUI/LiveView.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Run.hs
  configuration/configuration-mainnet.yaml
  nix/nixos/cardano-node-service.nix
  nix/nixos/chairman-as-a-service.nix
  nix/svclib.nix
  scripts/chairman.sh
  scripts/lib-node.sh
  scripts/mainnet.sh
Labels: priority medium

#648 Add default path for `GenesisFile` and make path relative to configuration yaml file
  cardano-config/cardano-config.cabal
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/app/chairman.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Run.hs
Labels: enhancement

#688 CAD-345 annotation constraints
  cabal.project
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
  cardano-node/src/Cardano/Node/Submission.hs
  cardano-node/src/Cardano/Tracing/MicroBenchmarking.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/NodeToNode.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Submission.hs
  stack.yaml
Labels: byron, maintenance

#690 Make cbor validation function pure
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Run.hs
Labels: maintenance

#701 CAD-737 eliding BlockFetchDecision messages
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: byron, maintenance, priority medium

#707 CAD-746 closed all listening ports by default
  benchmarking/chain-sync/configuration/log-config-byron-proxy.yaml
  benchmarking/chain-sync/configuration/log-configuration.yaml
  benchmarking/cluster3nodes/configuration/log-config-0.yaml
  benchmarking/cluster3nodes/configuration/log-config-1.yaml
  benchmarking/cluster3nodes/configuration/log-config-2.yaml
  benchmarking/cluster3nodes/configuration/log-config-explorer.yaml
  benchmarking/cluster3nodes/configuration/log-config-generator.yaml
  configuration/configuration-mainnet.yaml
  configuration/log-config-0.liveview.yaml
  configuration/log-config-0.yaml
  configuration/log-config-1.liveview.yaml
  configuration/log-config-1.yaml
  configuration/log-config-2.liveview.yaml
  configuration/log-config-2.yaml
Labels: byron

#696 Add create-byron-update-proposal command to cardano-cli
  cardano-config/src/Cardano/Config/CommonCLI.hs
  cardano-node/README.md
  cardano-node/app/cardano-cli.hs
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/CLI/Byron/Parsers.hs
  cardano-node/src/Cardano/CLI/Byron/UpdateProposal.hs
  cardano-node/src/Cardano/CLI/Key.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Parsers.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/Common/Parsers.hs
Labels: shelley mainnet, shelley testnet

#708 Use the new DNS pool for mainnet relays
  configuration/mainnet-topology.json
Labels: byron

#712 CAD-744 log a progress meter for block replay events
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: byron

#723 CAD-705 removed cardano-tx-generator
  README.md
  cabal.project
  cardano-node/README.md
  cardano-node/app/cardano-cli.hs
  cardano-node/cardano-node.cabal
  cardano-node/docs/tx-submit-using-tx-gen.md
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Parsers.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/Node/TxSubClient.hs
  cardano-tx-generator/ChangeLog.md
  cardano-tx-generator/LICENSE
  cardano-tx-generator/NOTICE
  cardano-tx-generator/README.md
  cardano-tx-generator/app/cardano-tx-generator.hs
  cardano-tx-generator/cardano-tx-generator.cabal
  cardano-tx-generator/docs/tx-submit-using-tx-gen.md
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Parsers.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Run.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Error.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/NodeToNode.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Submission.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Tx.hs
  cardano-tx-generator/test/Spec.hs
  scripts/generator.sh
  stack.yaml
Labels: byron, maintenance

#719 CAD-704 nightly CI job chain-sync not active anymore
  .buildkite/nightly.yml
Labels: byron, maintenance

#727 CAD-705 benchmarks removed
  benchmarking/chain-sync/README
  benchmarking/chain-sync/analyse-logs.sh
  benchmarking/chain-sync/benchmark-chain-sync-mainnet.sh
  benchmarking/chain-sync/ci.sh
  benchmarking/chain-sync/configuration/log-config-byron-proxy.yaml
  benchmarking/chain-sync/configuration/log-config-ci.yaml
  benchmarking/chain-sync/configuration/log-configuration.yaml
  benchmarking/chain-sync/configuration/topology-byron-proxy.yaml
  benchmarking/chain-sync/configuration/topology-local.yaml
  benchmarking/chain-sync/configuration/topology.yaml
  benchmarking/chain-sync/launch_mainnet_proxy.sh
  benchmarking/chain-sync/prepare-byron-proxy.sh
  benchmarking/chain-sync/start.sh
  benchmarking/chain-sync/tmux-session.sh
  benchmarking/cluster3nodes/.gitignore
  benchmarking/cluster3nodes/README
  benchmarking/cluster3nodes/analyse-blocks.sh
  benchmarking/cluster3nodes/benchmark.sh
  benchmarking/cluster3nodes/configuration/.gitignore
  benchmarking/cluster3nodes/configuration/log-config-0.yaml
  benchmarking/cluster3nodes/configuration/log-config-1.yaml
  benchmarking/cluster3nodes/configuration/log-config-2.yaml
  benchmarking/cluster3nodes/configuration/log-config-explorer.yaml
  benchmarking/cluster3nodes/configuration/log-config-generator.yaml
  benchmarking/cluster3nodes/configuration/log-config-genesis.yaml
  benchmarking/cluster3nodes/configuration/parameters
  benchmarking/cluster3nodes/configuration/protocol-params.json
  benchmarking/cluster3nodes/configuration/psql-settings.sh
  benchmarking/cluster3nodes/configuration/simple-topology-real-pbft-node-0.json
  benchmarking/cluster3nodes/configuration/simple-topology-real-pbft-node-1.json
  benchmarking/cluster3nodes/configuration/simple-topology-real-pbft-node-2.json
  benchmarking/cluster3nodes/configuration/simple-topology.json
  benchmarking/cluster3nodes/genesis.sh
  benchmarking/cluster3nodes/kill-session.sh
  benchmarking/cluster3nodes/prepare-explorer.sh
  benchmarking/cluster3nodes/run-3node-cluster.sh
  benchmarking/cluster3nodes/run_explorer.sh
  benchmarking/cluster3nodes/run_tx_generator.sh
  benchmarking/cluster3nodes/start.sh
Labels: byron, maintenance

#714 Add submit-byron-update-proposal command to cardano-cli
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
  cardano-node/README.md
  cardano-node/src/Cardano/CLI/Byron/Parsers.hs
  cardano-node/src/Cardano/CLI/Byron/UpdateProposal.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/CLI/Run.hs
  cardano-node/src/Cardano/CLI/Tx.hs
  cardano-node/src/Cardano/Node/Submission.hs
Labels: enhancement, shelley mainnet, shelley testnet
