Repository IntersectMBO/cardano-node, pull requests merged in 2020-07, with the labels that each got.

#1491 Fixed index.rst to display stakepool operations
  doc/index.rst
Labels: documentation

#1508 DOCS - removed nav components
  doc/index.rst
Labels: hydra-dont-build

#1544 Fixing the code split
  doc/reference/building-and-signing-tx.md
Labels: documentation

#1571 doc: various fixes
  doc/getting-started/understanding-config-files.md
  doc/index.rst
  doc/reference/building-and-signing-tx.md
  doc/reference/transactions.md
  doc/stake-pool-operations/keys_and_addresses.md
Labels: documentation

#1581 doc: Docs aligned with mainnet
  doc/getting-started/understanding-config-files.md
  doc/index.rst
  doc/logging-monitoring/logging.md
  doc/reference/building-and-signing-tx.md
  doc/reference/diagnosing-transactions.md
  doc/stake-pool-operations/KES_period.md
  doc/stake-pool-operations/core_relay.md
  doc/stake-pool-operations/getConfigFiles_AND_Connect.md
  doc/stake-pool-operations/keys_and_addresses.md
  doc/stake-pool-operations/node_keys.md
  doc/stake-pool-operations/register_key.md
  doc/stake-pool-operations/register_stakepool.md
  doc/stake-pool-operations/retire_stakepool.md
  doc/stake-pool-operations/simple_transaction.md
  doc/stake-pool-operations/start_your_nodes.md
Labels: documentation

#1580 Add legacy key generation documentation
  doc/stake-pool-operations/keys_and_addresses.md
Labels: documentation

#1587 doc: fix default port number prometheus
  doc/logging-monitoring/prometheus.md
Labels: documentation

#1599 CAD-1149: LiveView documentation.
  doc/index.rst
  doc/logging-monitoring/images/liveview-light.png
  doc/logging-monitoring/images/liveview.png
  doc/logging-monitoring/liveview.md
Labels: documentation, logging and monitoring
