Repository IntersectMBO/cardano-node, pull requests merged in 2020-04, with the labels that each got.

#757 CAD-790: Tracers for node version.
  cardano-node/src/Cardano/Node/Run.hs
Labels: byron

#743 CAD-666 Activate TraceForwarder plugin if needed.
  cabal.project
  cardano-config/cardano-config.cabal
  cardano-config/src/Cardano/Config/Logging.hs
  stack.yaml
Labels: byron, priority low

#732 Changes in node configuration and logging
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
Labels: byron, priority high

#749 Fixes docker image to align with 1.9
  nix/docker.nix
Labels: bug, nix, priority high

#777 CAD-805 Add TraceForwarderBK comments in default configs.
  configuration/defaults/liveview/config-0.yaml
  configuration/defaults/liveview/config-1.yaml
  configuration/defaults/liveview/config-2.yaml
  configuration/defaults/mainnet/configuration.yaml
  configuration/defaults/simpleview/config-0.yaml
  configuration/defaults/simpleview/config-1.yaml
  configuration/defaults/simpleview/config-2.yaml
Labels: priority medium, shelley testnet

#778 CAD-662 Capture GHC RTS metrics.
  cardano-config/src/Cardano/Config/Logging.hs
Labels: priority high

#679 CAD-742: Chairman's remainder of maintenance: topology & log analysis
  .gitignore
  cardano-config/src/Cardano/Config/Protocol.hs
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
  nix/nixos/cardano-cluster-service.nix
  nix/nixos/tests/chairmans-cluster.nix
  nix/svclib.nix
  scripts/README.md
  scripts/chairmans-cluster/README.org
  scripts/chairmans-cluster/cluster-log-split.sh
  scripts/chairmans-cluster/cluster-test.sh
  scripts/chairmans-cluster/unlogging.sh
  scripts/cluster-log.sh
Labels: byron, chairman, maintenance

#779 Isolate node socket in Docker image
  default.nix
  nix/docker.nix
  nix/scripts.nix
Labels: nix, priority high

#785 CAD-828 scripts: fixes; factor; profiling; verbosity; --nix mode (new default)
  .gitignore
  configuration/defaults/simple-dns/topology.json
  nix/haskell.nix
  scripts/chairman.sh
  scripts/chairmans-cluster/cluster-test.sh
  scripts/common.sh
  scripts/genesis.sh
  scripts/get-default-key-address.sh
  scripts/issue-genesis-utxo-expenditure.sh
  scripts/issue-utxo-expenditure.sh
  scripts/lib-cli.sh
  scripts/lib-cluster.sh
  scripts/lib-nix.sh
  scripts/lib-node.sh
  scripts/lib.sh
  scripts/mainnet.sh
  scripts/shelley-testnet-dns.sh
  scripts/shelley-testnet-live.sh
  scripts/shelley-testnet.sh
  scripts/shelley-testnet.tmux0.sh
  scripts/shelley-testnet.tmux1.sh
  scripts/submit-tx.sh
  shell.nix
Labels: nix

#791 CAD-828: hotfix for tmux & graceful Nix build failure handling
  scripts/common.sh
  scripts/lib-cluster.sh
  scripts/lib-nix.sh
  scripts/lib-node.sh
  scripts/lib.sh
  scripts/shelley-testnet.tmux1.sh
Labels: bug, nix, priority high

#760 CAD-710 textual log output
  cabal.project
  cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Node/Submission.hs
  cardano-node/src/Cardano/Tracing/MicroBenchmarking.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  stack.yaml
Labels: byron, maintenance, priority medium

#805 CAD-830: refactor log/trace configuration
  cardano-config/cardano-config.cabal
  cardano-config/src/Cardano/Config/Logging.hs
  cardano-config/src/Cardano/Config/TraceConfig.hs
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: enhancement, maintenance, priority medium

#809 Updated ouroboros-network dependency
  cabal.project
  cardano-api/src/Cardano/Api/TxSubmit.hs
  cardano-node/src/Cardano/CLI/Ops.hs
  cardano-node/src/Cardano/Chairman.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Node/Submission.hs
  cardano-node/src/Cardano/Node/TUI/LiveView.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  stack.yaml
Labels: networking

#825 Add missing preprocessor directives for defining UNIX macro in Cardano.CLI.Genesis
  cardano-cli/src/Cardano/CLI/Genesis.hs
Labels: maintenance

#821 Allow to make use of sourcesOverrides for scripts
  nix/scripts.nix
Labels: devops

#831 CAD-792: bump monitoring for non-API-breaking efficiency improvements
  cabal.project
  cardano-config/src/Cardano/Config/Logging.hs
  cardano-config/src/Cardano/TracingOrphanInstances/Network.hs
  stack.yaml
Labels: maintenance, priority low

#773 CAD-791 eliding addtocurrentchain messages
  cabal.project
  cardano-node/src/Cardano/Tracing/Tracers.hs
  stack.yaml
Labels: maintenance, priority medium

#827 CAD-763 adapt configuration for LiveView
  configuration/defaults/mainnet/configuration.yaml
Labels: maintenance, priority medium

#839 Logging configuration: allow the node metadata to be seen
  configuration/defaults/mainnet/configuration.yaml
Labels: maintenance, priority medium

#776 CAD-815: shutdown API and node exit on ChainDB slot sync limit
  .gitignore
  Makefile
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/Common/Parsers.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Node/Shutdown.hs
  configuration/defaults/excommunicated/topology.json
  configuration/defaults/mainnet-silent/configuration.yaml
  configuration/defaults/mainnet-silent/genesis.json
  configuration/defaults/mainnet-silent/topology.json
  configuration/defaults/mainnet-via-fetcher/configuration.yaml
  configuration/defaults/mainnet-via-fetcher/genesis.json
  configuration/defaults/mainnet-via-fetcher/topology.json
  scripts/common.sh
  scripts/lib-node.sh
  scripts/lib.sh
  scripts/mainnet-via-fetcher.sh
  scripts/mainnet.sh
  shell.nix
Labels: enhancement, priority medium

#804 Implement byron vote creation and submission
  README.md
  cardano-cli/cardano-cli.cabal
  cardano-cli/src/Cardano/CLI/Byron/Parsers.hs
  cardano-cli/src/Cardano/CLI/Byron/Run.hs
  cardano-cli/src/Cardano/CLI/Byron/UpdateProposal.hs
  cardano-cli/src/Cardano/CLI/Byron/Vote.hs
  cardano-cli/src/Cardano/CLI/Ops.hs
  cardano-cli/src/Cardano/CLI/Parsers.hs
  cardano-cli/src/Cardano/CLI/Run.hs
  cardano-config/src/Cardano/Config/Types.hs
Labels: shelley testnet

#855 Remove hard-coded `EpochSlots` in validate-cbor command
  README.md
  cardano-cli/src/Cardano/CLI/Ops.hs
  cardano-cli/src/Cardano/CLI/Parsers.hs
  cardano-config/src/Cardano/Config/Types.hs
Labels: maintenance

#858 scripts: don't even attempt to use Nix in non-`--nix` modes
  scripts/lib.sh
Labels: bug, nix, priority low

#862 Update parsers for cardano-cli's issue-op-cert
  cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
  cardano-cli/src/Cardano/CLI/Shelley/Run.hs
  cardano-config/src/Cardano/Config/Shelley/OCert.hs
Labels: maintenance

#863 CAD-803 TraceLabelPeers FetchDecision: repeated (<>) on Object loses information
  cardano-config/src/Cardano/TracingOrphanInstances/Network.hs
Labels: bug, maintenance, priority low

#842 CAD-894 log message if count or time diff reached
  cabal.project
  cardano-node/src/Cardano/Tracing/Tracers.hs
  stack.yaml
Labels: bug, priority medium
