Repository IntersectMBO/cardano-node, pull requests merged in 2020-05, with the labels that each got.

#875 CAD-901: Peers list
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: priority medium, shelley testnet

#877 CAD-932, CAD-902: update scripts
  .gitignore
  README.md
  scripts/README.md
  scripts/chairman.sh
  scripts/issue-genesis-utxo-expenditure.sh
  scripts/issue-utxo-expenditure.sh
  scripts/lib-cli.sh
  scripts/lib-cluster.sh
  scripts/lib-nix.sh
  scripts/lib-node.sh
  scripts/lib.sh
  scripts/mainnet-via-fetcher.sh
  scripts/submit-tx.sh
Labels: maintenance, priority low

#879 removed -Werror from stack.yaml
  stack.yaml
Labels: shelley testnet

#874 Refactor protocol folder in cardano-config
  cardano-config/cardano-config.cabal
  cardano-config/src/Cardano/Config/Byron/Protocol.hs
  cardano-config/src/Cardano/Config/Mock/Protocol.hs
  cardano-config/src/Cardano/Config/Protocol.hs
  cardano-config/src/Cardano/Config/Protocol/Types.hs
  cardano-config/src/Cardano/Config/Shelley/Protocol.hs
  cardano-config/src/Cardano/Config/Types.hs
  cardano-node/src/Cardano/Common/LocalSocket.hs
Labels: maintenance

#876 Regroup byron commands
  README.md
  cardano-cli/src/Cardano/CLI/Byron/Parsers.hs
  cardano-cli/src/Cardano/CLI/Byron/Run.hs
  cardano-cli/src/Cardano/CLI/Byron/UpdateProposal.hs
  cardano-cli/src/Cardano/CLI/Byron/Vote.hs
Labels: maintenance

#892 CAD-878: Trace node up time.
  cardano-node/src/Cardano/Node/Run.hs
Labels: priority medium, shelley testnet

#890 Stake address and stake pool delegation certificates
  cardano-api/cardano-api.cabal
  cardano-api/src/Cardano/Api.hs
  cardano-api/src/Cardano/Api/CBOR.hs
  cardano-api/src/Cardano/Api/Types.hs
  cardano-api/src/Cardano/Api/View.hs
  cardano-api/test/Test/Cardano/Api/CBOR.hs
  cardano-api/test/Test/Cardano/Api/Gen.hs
  cardano-api/test/Test/Cardano/Api/View.hs
  cardano-cli/src/Cardano/CLI/Delegation.hs
  cardano-cli/src/Cardano/CLI/Ops.hs
  cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
  cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
  cardano-config/src/Cardano/Config/Types.hs
Labels: shelley testnet

#937 CAD-900: Node traces processed txs num.
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Node/TUI/LiveView.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: priority medium, shelley testnet

#964 CAD-970 disable output to console if LiveView active
  cardano-config/src/Cardano/Config/Logging.hs
  configuration/defaults/byron-mainnet/configuration.yaml
Labels: Pioneer, priority high, shelley testnet

#965 CAD-971 check required tracers in LiveView
  cardano-node/src/Cardano/Node/Run.hs
Labels: Pioneer, priority medium, shelley testnet

#978 newer 'systemd' package needed for compilation with stack
  stack.yaml
Labels: bug, maintenance

#1066 Improve shelley cli tx-in parser
  cardano-api/src/Cardano/Api/Convert.hs
  cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
Labels: cli revision

#1069 Add CLI command to get Pool Id
  cardano-api/ChangeLog.md
  cardano-cli/src/Cardano/CLI/Shelley/Commands.hs
  cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
  cardano-cli/src/Cardano/CLI/Shelley/Run/Pool.hs
Labels: cli revision

#1091 CAD-1132 trace block size in AdoptedBlock event
  cardano-config/src/Cardano/TracingOrphanInstances/Consensus.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: enhancement, priority medium, shelley testnet
