Repository IntersectMBO/cardano-node, pull requests merged in 2020-01, with the labels that each got.

#462 ToObjectOrphans: Fix typos in some keys
  cardano-node/src/Cardano/Tracing/ToObjectOrphans.hs
Labels: bug, byron

#491 CAD-438 replacement Prometheus interface
  cabal.project
  nix/.stack.nix/contra-tracer.nix
  nix/.stack.nix/iohk-monitoring.nix
  nix/.stack.nix/lobemo-backend-aggregation.nix
  nix/.stack.nix/lobemo-backend-editor.nix
  nix/.stack.nix/lobemo-backend-ekg.nix
  nix/.stack.nix/lobemo-backend-monitoring.nix
  nix/.stack.nix/lobemo-scribe-systemd.nix
  nix/.stack.nix/tracer-transformers.nix
  stack.yaml
Labels: bug, byron

#500 [CAD-417] Considering NFData instances.
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/Node/TUI/LiveView.hs
  nix/.stack.nix/cardano-node.nix
Labels: byron, enhancement

#494 CAD-411 default tracers
  benchmarking/chain-sync/configuration/log-configuration.yaml
  benchmarking/cluster3nodes/configuration/log-config-0.yaml
  benchmarking/cluster3nodes/configuration/log-config-1.yaml
  benchmarking/cluster3nodes/configuration/log-config-2.yaml
  cardano-config/src/Cardano/Config/Types.hs
  configuration/log-configuration.yaml
Labels: byron

#501 disable nightly benchmark against 'testnet'
  .buildkite/nightly.yml
Labels: byron

#502 CAD-425 logging to journald
  cabal.project
  cardano-config/src/Cardano/Config/Logging.hs
  configuration/log-configuration.yaml
  nix/.stack.nix/contra-tracer.nix
  nix/.stack.nix/iohk-monitoring.nix
  nix/.stack.nix/lobemo-backend-aggregation.nix
  nix/.stack.nix/lobemo-backend-editor.nix
  nix/.stack.nix/lobemo-backend-ekg.nix
  nix/.stack.nix/lobemo-backend-monitoring.nix
  nix/.stack.nix/lobemo-scribe-systemd.nix
  nix/.stack.nix/tracer-transformers.nix
  stack.yaml
Labels: byron

#505 CAD-457 tx generator: fix main tx creation
  cardano-node/src/Cardano/CLI/Tx/Generation.hs
Labels: bug, byron
