Repository IntersectMBO/cardano-node, pull requests merged in 2020-12, with the labels that each got.

#2166 Edge node nixos test fixes
  default.nix
  nix/nixos/tests/cardano-node-edge.nix
  nix/pkgs.nix
  release.nix
Labels: nix

#2178 Network tracers
  cardano-node/src/Cardano/Tracing/Constraints.hs
  cardano-node/src/Cardano/Tracing/OrphanInstances/Network.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: networking

#1743 [DOCS] Update install.md
  doc/getting-started/install.md
Labels: documentation
