Repository IntersectMBO/cardano-node, pull requests merged in 2021-11, with the labels that each got.

#3363 Integration with peer2peer networking
  bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/NodeToNode.hs
  cabal.project
  cardano-node-chairman/test/Spec/Chairman/Chairman.hs
  cardano-node-chairman/testnet/Testnet/Commands/Byron.hs
  cardano-node-chairman/testnet/Testnet/Commands/Shelley.hs
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/Node/Configuration/POM.hs
  cardano-node/src/Cardano/Node/Configuration/Socket.hs
  cardano-node/src/Cardano/Node/Configuration/Topology.hs
  cardano-node/src/Cardano/Node/Configuration/TopologyP2P.hs
  cardano-node/src/Cardano/Node/Parsers.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Tracing/Config.hs
  cardano-node/src/Cardano/Tracing/OrphanInstances/Consensus.hs
  cardano-node/src/Cardano/Tracing/OrphanInstances/Network.hs
  cardano-node/src/Cardano/Tracing/Peer.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
  cardano-node/test/Test/Cardano/Node/Gen.hs
  cardano-node/test/Test/Cardano/Node/POM.hs
  cardano-testnet/cardano-testnet.cabal
  cardano-testnet/src/Testnet/Byron.hs
  cardano-testnet/src/Testnet/Cardano.hs
  cardano-testnet/src/Testnet/Shelley.hs
  cardano-testnet/testnet/Testnet/Commands/Byron.hs
  cardano-testnet/testnet/Testnet/Commands/Cardano.hs
  cardano-testnet/testnet/Testnet/Commands/Shelley.hs
  configuration/cardano/mainnet-p2p-toplogy.json
  configuration/chairman/byron-shelley/configuration.yaml
  configuration/chairman/defaults/simpleview/config-0.yaml
  configuration/chairman/defaults/simpleview/config-1.yaml
  configuration/chairman/defaults/simpleview/config-2.yaml
  configuration/chairman/shelley-only/configuration.yaml
  configuration/defaults/byron-mainnet/configuration.yaml
  doc/getting-started/understanding-config-files.md
  nix/nixos/cardano-node-service.nix
Labels: networking

#3359 tx-generator: derive Plutus budged automatically
  bench/script/test-plutus-to-file.json
  bench/script/test-plutus.json
  bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx.hs
  bench/tx-generator/src/Cardano/Benchmarking/PlutusExample.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Aeson.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Example.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Types.hs
  bench/tx-generator/src/Cardano/Benchmarking/Wallet.hs
  bench/tx-generator/tx-generator.cabal
  nix/nixos/tx-generator-service.nix
Labels: enhancement

#3398 tx-generator: fix some bugs
  bench/script/test-full-auto.json
  bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Env.hs
  bench/tx-generator/src/Cardano/Benchmarking/Types.hs
  bench/tx-generator/src/Cardano/Benchmarking/Wallet.hs
  nix/nixos/tx-generator-service.nix
  nix/workbench/profiles/adhoc.jq
Labels: bug
