Repository IntersectMBO/cardano-node, pull requests merged in 2021-12, with the labels that each got.

#3411 tx-generator: Use generic JSON instances
  bench/tx-generator/src/Cardano/Benchmarking/Command.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Aeson.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/AesonLegacy.hs
  bench/tx-generator/tx-generator.cabal
  nix/nixos/tx-generator-service.nix
Labels: enhancement

#3415 tx-generator: add missing DSUM instances
  bench/script/test-full-auto.ljson
  bench/script/test-large.ljson
  bench/script/test-plutus-to-file.json
  bench/script/test-plutus-to-file.ljson
  bench/script/test-plutus.ljson
  bench/tx-generator/src/Cardano/Benchmarking/Script/Aeson.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/AesonLegacy.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Setters.hs
Labels: bug

#3425 tx-generator: towards stand-alone mode
  bench/script/test-stand-alone.json
  bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/LocalProtocolDefinition.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Action.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Aeson.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/AesonLegacy.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Env.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Setters.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Store.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Types.hs
  bench/tx-generator/src/Cardano/Benchmarking/Tracer.hs
  bench/tx-generator/src/Cardano/Benchmarking/Wallet.hs
Labels: enhancement

#3426 tx-generator: make the used key/address explicit
  bench/script/test-full-auto.ljson
  bench/script/test-large.ljson
  bench/script/test-plutus-to-file.json
  bench/script/test-plutus-to-file.ljson
  bench/script/test-plutus.ljson
  bench/script/test-stand-alone.json
  bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Example.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Types.hs
  nix/nixos/tx-generator-service.nix
Labels: enhancement

#3427 tx-generator: add literate keys and manual funds.
  bench/script/test-stand-alone.json
  bench/tx-generator/src/Cardano/Benchmarking/Script/Action.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Types.hs
Labels: enhancement

#3436 tx-generator: set default: query local node for protocol parameters
  bench/tx-generator/src/Cardano/Benchmarking/Script.hs
Labels: bug

#3444 tx-generator: bug fix: breakup large STM transactions.
  bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/Submission.hs
  bench/tx-generator/src/Cardano/Benchmarking/Tracer.hs
  bench/tx-generator/src/Cardano/Benchmarking/Types.hs
Labels: bug

#3434 Tracing improvements
  cardano-node/src/Cardano/Tracing/OrphanInstances/Network.hs
  cardano-node/src/Cardano/Tracing/Startup.hs
Labels: networking, logging and monitoring
