Repository IntersectMBO/cardano-node, pull requests merged in 2021-06, with the labels that each got.

#2834 Win32-network: use the latest version
  cabal.project
Labels: Windows, networking

#2841 Network trancers should be owned by the networking team
  CODEOWNERS
Labels: networking

#2676 CAD-2894 add wallet
  bench/script/test-wallet.json
  bench/tx-generator/src/Cardano/Benchmarking/FundSet.hs
  bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx.hs
  bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/Submission.hs
  bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/SubmissionClient.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Action.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Aeson.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
  bench/tx-generator/src/Cardano/Benchmarking/Script/Example.hs
  bench/tx-generator/src/Cardano/Benchmarking/Types.hs
  bench/tx-generator/src/Cardano/Benchmarking/Wallet.hs
  bench/tx-generator/tx-generator.cabal
Labels: enhancement
