Repository IntersectMBO/cardano-node, pull requests merged in 2022-06, with the labels that each got.

#3796 Docs: update Haskell installation method and mention libsecp256k1
  doc/getting-started/install.md
Labels: documentation

#3896 Install a dummy SIGHUP handler for non p2p mode
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/src/Cardano/Node/Startup.hs
  cardano-node/src/Cardano/Node/Tracing/Tracers/Startup.hs
  cardano-node/src/Cardano/Tracing/Startup.hs
Labels: networking

#4022 cardano-tracer: remove Cardano.Node prefix
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/EraSettings.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/Nodes.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/Peers.hs
Labels: RTView, tracing

#4038 Fix for eliding of the ChainDB tracer
  cardano-node/src/Cardano/Tracing/Config.hs
  cardano-node/src/Cardano/Tracing/Tracers.hs
Labels: bug

#4000 Further explain the `libsodium` installation
  doc/getting-started/install.md
Labels: documentation

#4011 CAD-3915 define the `BackingStoreSelector` flag
  bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
  cabal.project
  cardano-api/src/Cardano/Api/Query.hs
  cardano-client-demo/ChainSyncClientWithLedgerState.hs
  cardano-client-demo/LedgerState.hs
  cardano-client-demo/StakeCredentialHistory.hs
  cardano-node/cardano-node.cabal
  cardano-node/src/Cardano/Node/Configuration/LedgerDB.hs
  cardano-node/src/Cardano/Node/Configuration/POM.hs
  cardano-node/src/Cardano/Node/Parsers.hs
  cardano-node/src/Cardano/Node/Run.hs
  cardano-node/test/Test/Cardano/Node/POM.hs
  nix/lmdb-mingw.patch
  nix/pkgs.nix
Labels: consensus, UTxO-HD 📒💽

#4077 RTView: notifications (email)
  cardano-tracer/cardano-tracer.cabal
  cardano-tracer/src/Cardano/Tracer/Acceptors/Client.hs
  cardano-tracer/src/Cardano/Tracer/Acceptors/Run.hs
  cardano-tracer/src/Cardano/Tracer/Acceptors/Server.hs
  cardano-tracer/src/Cardano/Tracer/Acceptors/Utils.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/Logs/File.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Notifications/Check.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Notifications/Email.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Notifications/Send.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Notifications/Settings.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Notifications/Timer.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Notifications/Types.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Notifications/Utils.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Run.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/SSL/Certs.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/System.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/CSS/Own.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/HTML/Body.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/HTML/Main.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/HTML/NoNodes.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/HTML/Notifications.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/Img/Icons.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/Notifications.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/Utils.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/EKG.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/Errors.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/Nodes.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/Peers.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/Reload.hs
  cardano-tracer/src/Cardano/Tracer/Handlers/RTView/Update/Utils.hs
  cardano-tracer/src/Cardano/Tracer/Run.hs
  cardano-tracer/src/Cardano/Tracer/Utils.hs
  cardano-tracer/test/Cardano/Tracer/Test/Acceptor.hs
  cardano-tracer/test/cardano-tracer-test.hs
Labels: RTView
