Repository IntersectMBO/cardano-node, pull requests merged in 2023-01, with the labels that each got.

#4408 Allow assembling transactions with no witnesses
  cardano-cli/ChangeLog.md
  cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
Labels: Stale

#4753 Export SubmitResult from Cardano.Api
  cardano-api/src/Cardano/Api.hs
Labels: Client API

#4761 Fix bug in hash computation in 'cardano-cli genesis create-cardano'.
  cardano-cli/src/Cardano/CLI/Shelley/Run/Genesis.hs
Labels: bug
